# Generated by Django 4.0.6 on 2023-06-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PURCHASE', '0005_productformmodel_remove_product_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productForm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PURCHASE.productformmodel'),
        ),
    ]
