# Generated by Django 4.0.6 on 2023-06-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PURCHASE', '0006_product_productform'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='product_image/%Y/%m/%d/'),
        ),
    ]
